### DISCUSSION TITLE
How can I block bots and crawlers on my ngrok endpoints?

### DISCUSSION THREAD

**Discussion by joelhans** [ngrok/ngrok#36] [Q&A] [answered]
As a secondary question, why doesn't ngrok block these automated requests automatically?

**Comment by joelhans** [comment, marked as answer]
You can use the [Traffic Policy module](https://ngrok.com/docs/http/traffic-policy/) in multiple ways to forbid or outright deny all or specific bots that might request and utilize the data on your endpoints.

For example, you can add a custom response for the `/robots.txt` path that forbids bots:

```yaml
# snippet
---
inbound:
  - expressions:
      - "req.url.contains('/robots.txt')"
    actions:
      - type: "custom-response"
        config:
          status_code: 200
          content: "User-agent: *\r\nDisallow: /"
          headers:
            content-type: "text/plain"
```

For more options, like denying specific search/AI bots using their user agents, see our blog post: https://ngrok.com/blog-post/search-ai-bots-traffic-policy

--

For the second question—while ngrok does have robust [DDoS protection](https://ngrok.com/docs/network-edge/#ddos-protection) to protect your endpoints from know attacks, we don't block any traffic to your endpoints that you haven't explicitly configured. We do that so that you remain in control of how your endpoints operate and who—or what—can access them.
