### ISSUE TITLE
Cannot create ngrok.yml configuration for https -> https forwarding

### ISSUE THREAD

**Issue by franck102** [ngrok/ngrok#50]
I am following the documentation(https://ngrok.com/docs/agent/config/v3/) to try and create a config file to forward to a local HTTPS server:

```yaml
version: 3
agent:
  authtoken: xxx
endpoints:
  - name: xxx
    url: https://mongoose-tough-blindly.ngrok-free.app
    description: "xxx"
    upstream:
      url: https://macbook:9090
```
... and ngrok thinks I want a TLS tunnel:

```
> ngrok config check
ERROR:  Tunnel 'Passmate Dev Franck' specifies an invalid or malformed address 'https://macbook:9090': unsupported scheme for tls tunnel: https

> $ ngrok version
ngrok version 3.16.1

```

Am I missing something obvious? I don't see where I can specify that I want an https tunnel?

Please also note that the upstream.protocol field is described as accepting HTTP / HTTPS in the summary tables, vs. http1 / http2 in the detailed description.
