### ISSUE TITLE
Probally issue using ngrok Docker Compose, "Attaching to ngrok" 

### ISSUE THREAD

**Issue by srlightt** [ngrok/ngrok#55]
my docker compose:
```yaml
services:
  ngrok0:
    image: ngrok/ngrok:3-alpine
    network_mode: "host"
    environment:
      NGROK_AUTHTOKEN: 000
    command:
      - "http"
      - "8080"
```
but the container returns no output or log, only “Attaching ngrok0”

**Comment by russorat** [comment]
@srlightt thanks for the issue. your docker compose looks fine to me. If you add additional logging params, you will see the output from ngrok with the url:

```
services:
  ngrok0:
    image: ngrok/ngrok:3-alpine
    network_mode: "host"
    environment:
      NGROK_AUTHTOKEN: 000
    command:
      - "http"
      - "8080"
      - "--log"
      - "stdout"
```

```
❯ docker compose up                                                                                               60s  3.0.0
[+] Running 2/0
 ✔ Container ngrok-ngrok-12-static-site-1  Created                                                                                                                         0.0s
 ✔ Container ngrok-ngrok-12-ngrok0-1       Recreated                                                                                                                       0.0s
Attaching to ngrok0-1, static-site-1
ngrok0-1       | t=2024-10-25T20:15:46+0000 lvl=info msg="open config file" path=/var/lib/ngrok/ngrok.yml err=nil
ngrok0-1       | t=2024-10-25T20:15:46+0000 lvl=info msg="open config file" path=/var/lib/ngrok/auth-config.yml err=nil
ngrok0-1       | t=2024-10-25T20:15:46+0000 lvl=info msg="starting web service" obj=web addr=0.0.0.0:4040 allow_hosts=[]
ngrok0-1       | t=2024-10-25T20:15:46+0000 lvl=info msg="client session established" obj=tunnels.session
ngrok0-1       | t=2024-10-25T20:15:46+0000 lvl=info msg="tunnel session started" obj=tunnels.session
ngrok0-1       | t=2024-10-25T20:15:46+0000 lvl=info msg="started tunnel" obj=tunnels name=command_line addr=http://localhost:80 url=https://bed2d5c92b48.ngrok.app
```
